import './globals.css'
import { Inter } from 'next/font/google'
import Session from './providers/session'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Marty Mart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Session>
      <body className={inter.className}>{children}</body>
      </Session> 
    </html>
  )
}
